package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"apiGrapqlEntgo/graph/generated"
	"apiGrapqlEntgo/graph/model"
	"context"
	"fmt"
)

// CreateProfessor is the resolver for the createProfessor field.
func (r *mutationResolver) CreateProfessor(ctx context.Context, input model.NewProfessor) (*model.Professor, error) {
	panic(fmt.Errorf("not implemented: CreateProfessor - createProfessor"))
}

// RemoveProfessor is the resolver for the removeProfessor field.
func (r *mutationResolver) RemoveProfessor(ctx context.Context, id string) (*model.Professor, error) {
	panic(fmt.Errorf("not implemented: RemoveProfessor - removeProfessor"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
