// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Course struct {
	ID             int    `json:"id"`
	Year           int    `json:"year"`
	Period         int    `json:"period"`
	ProfessorID    string `json:"professor_id"`
	SubjectID      string `json:"subject_id"`
	CreatedAt      string `json:"created_at"`
	LastModifiedAt string `json:"last_modified_at"`
}

type NewCourse struct {
	Year        int    `json:"year"`
	Period      int    `json:"period"`
	ProfessorID string `json:"professor_id"`
	SubjectID   string `json:"subject_id"`
}

type NewProfessor struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	LastName  string `json:"last_name"`
	BirthDate string `json:"birth_date"`
}

type NewSubject struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Active      bool   `json:"active"`
}

type Professor struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	LastName       string `json:"last_name"`
	BirthDate      string `json:"birth_date"`
	CreatedAt      string `json:"created_at"`
	LastModifiedAt string `json:"last_modified_at"`
}

type Subject struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	Active         bool   `json:"active"`
	CreatedAt      string `json:"created_at"`
	LastModifiedAt string `json:"last_modified_at"`
}
