// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Professor is the predicate function for professor builders.
type Professor func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)
